### ISSUE TITLE
Please Update to 1.20.2

### ISSUE THREAD

**Issue by sternschnaube** [FxMorin/MoreCullingExtra#12]
Was a problem with More Culling in first place, can't verify right now if More Culling Extra is compatible with 1.20.2, since More Culling doesn't works currently.

**Comment by sternschnaube** [comment]
While trying to connect to an server, this error came:

java.lang.NullPointerException: Cannot read field "field_1352" because "$$7" is null
	at net.minecraft.class_761.method_3257(class_761.java:1753)
	at net.minecraft.class_761.method_22710(class_761.java:1009)
	at net.minecraft.class_757.method_3188(class_757.java:1113)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by FxMorin** [comment]
Can you try with MoreCulling v0.21.0
